paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Return all products
      responses:
        '200':
          description: All products
          content:
            application/json:
              schemas:
                $ref: '#/components/schemas/Products'
              example:
                _id: ObjectId("63e445cf5b322796099c7a0e"),
                title: "PlayStation 5"
                description: "Consola UltraSlim 1TB"
                code: "pok210"
                price": 240000
                stock: 53
                category: "Electro"
                owner: "adminCoder@coder.com"
                __v: 0
        '400':
          description: Bad request.
        '404':
          description: Not Found.
        '405':
          description: Method not allowed.
        '500':
          description: Unexpected error.
    post:
      tags:
        -Products
      summary: Add one product
      description: 'If you want to add a product you have to send a petition to this endpoint and complete the required fields'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Products'
            example:
              title: "PlayStation 5"
              description: "Consola UltraSlim 1TB"
              code: "pok210"
              price: 240000
              stock: 53
              category: "Electro"
              owner: "adminCoder@coder.com"
      responses:
        '200':
          description: Product added
          content:
            application/json:
              schemas:
                $ref: '#/components/schemas/Products'
              example:
              _id: ObjectId("63e445cf5b322796099c7a0e")
              title: "PlayStation 5"
              description: "Consola UltraSlim 1TB"
              code: "pok210"
              price: 240000
              stock: 53
              category: "Electro"
              owner: "adminCoder@coder.com"
              __v: 0
        '400':
          description: Bad request.
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.
        '405':
          description: Method not allowed.
        '500':
          description: Unexpected error.
  /api/products/{id}:
    get:
      tags:
        -Products
      summary: Get one product by ID
      description: 'If you want to get a product by id you have to send a petition to this endpoint with the required data bellow'
      parameters:
        - name: id
          in: path
          description: Product ID
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schemas:
                $ref: '#/components/schemas/Products'
              example:
              _id: ObjectId("63e445cf5b322796099c7a0e")
              title: "PlayStation 5"
              description: "Consola UltraSlim 1TB"
              code: "pok210"
              price: 240000
              stock: 53
              category: "Electro"
              owner: "adminCoder@coder.com"
              __v: 0
        '400':
          description: Bad request.
        '404':
          description: Not Found.
        '405':
          description: Method not allowed.
        '500':
          description: Unexpected error.
    put:
      tags:
        -Products
      summary: Update a product
      description: "If you want to update a product you have to send a petition to this endpoint with the required data bellow. In the request body just send the values you want to change"
      parameters:
        - name: id
          in: path
          description: Product identifier
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Products"
            example:
              description: 'Consola UltraSlim 1TB' 
      responses:
        "200":
          description: Updates a product's value
          content:
            application/json:
              schemas:
                $ref: "#/components/schemas/Products"
              example:
                _id: ObjectId('64659c0d0f5c8bf955653bfa')
                title: "PlayStation 5"
                description: "Consola UltraSlim 1TB"
                code: ""
                price: 240000
                stock: 53
                category: "Electro"
                owner: "adminCoder@coder.com"
                __v: 0
        "400":
          description: Bad request.
        "401":
          description: Authorization information is missing or invalid.
        "404":
          description: Not Found.
        "405":
          description: Invalid Method.
        "500":
          description: Unexpected error.
    delete:
      tags:
        - Products
      summary: Deletes one product by id
      description: "If you want to delete a product you have to send a petition to this endpoint with the required data bellow."
      parameters:
        - name: id
          in: path
          description: Product identifier
      responses:
        "200":
          description: Deletes the product
        "400":
          description: Bad request.
        "401":
          description: Authorization information is missing or invalid.
        "404":
          description: Not Found.
        "405":
          description: Invalid Method.
        "500":
          description: Unexpected error.
components:
  schemas:
    Products:
      type: object
      properties:
        title:
          type: string
          required: true
        description:
          type: string
          required: true
        code:
          type: string
          required: true
          unique: true
        price:
          type: number
          required: true
        stock:
          type: number
          required: true
        category:
          type: string
          required: true
        owner:
          type: string
          default: "adminCoder@coder.com"
      example:
        _id: ObjectId('64659c0d0f5c8bf955653bfa')
        title: "PlaySation 5"
        description: "Consola UltraSlim 1TB"
        code: "pok210"
        price: 240000
        stock: 53
        category: "Electro"
        owner: "adminCoder@coder.com"
        __v: 0



